### ISSUE TITLE
Scraper container output stagnant after 1337x finishes

### ISSUE THREAD

**Issue by REEEEE-B00T** [Gabisonfire/torrentio-scraper-sh#22]
Docker logs torrentio-self-host-scraper1 shows links scraped up until 1337x finishes and then there is no additional log activity.
Not sure if this is all of the scraper capability currently on this fork or not, but if it is, it might be worth adding a blurb in the readme. 
Scraper was only running for ~1 hour.

**Comment by funkypenguin** [comment]
AFAIK this is normal, unless you run the scraper with `ENABLE_SCHEDULING`, in which case it'll sit and do nothing anyway, until its 4h cron kicks in :)

See the logic at https://github.com/Gabisonfire/torrentio-scraper-sh/blob/master/scraper/scheduler/scheduler.js

**Comment by trulow** [comment]
@funkypenguin Did you encounter any errors enableing - ENABLE_SCHEDULING=true for the scraper?

When I tried it I get the following

```
2024-02-01T18:19:06.648694453Z       Object.keys(cb).forEach(function (k) {

2024-02-01T18:19:06.648701042Z              ^

2024-02-01T18:19:06.648705242Z 

2024-02-01T18:19:06.648709370Z TypeError: Cannot convert undefined or null to object

2024-02-01T18:19:06.648722580Z     at Function.keys (<anonymous>)

2024-02-01T18:19:06.648727140Z     at wrapper (/home/node/app/node_modules/wrappy/wrappy.js:27:14)

2024-02-01T18:19:06.648730948Z     at Function.Client.scrape (/home/node/app/node_modules/bittorrent-tracker/client.js:120:8)

2024-02-01T18:19:06.648735060Z     at /home/node/app/lib/torrent.js:47:16

2024-02-01T18:19:06.648738844Z     at /home/node/app/node_modules/async/dist/async.js:2583:44

2024-02-01T18:19:06.648742612Z     at eachOfArrayLike (/home/node/app/node_modules/async/dist/async.js:506:13)

2024-02-01T18:19:06.648758836Z     at eachOf (/home/node/app/node_modules/async/dist/async.js:626:16)

2024-02-01T18:19:06.648763153Z     at awaitable (/home/node/app/node_modules/async/dist/async.js:211:32)

2024-02-01T18:19:06.648767133Z     at Object.eachLimit (/home/node/app/node_modules/async/dist/async.js:2686:16)

2024-02-01T18:19:06.648771065Z     at Object.awaitable (/home/node/app/node_modules/async/dist/async.js:211:32)

2024-02-01T18:19:06.648774908Z     at /home/node/app/lib/torrent.js:46:11
```

**Comment by ash32152** [comment]
> @funkypenguin Did you encounter any errors enableing - ENABLE_SCHEDULING=true for the scraper?
> 
> When I tried it I get the following output.
> 
> ```
> 2024-02-01T18:19:06.648694453Z       Object.keys(cb).forEach(function (k) {
> 
> 2024-02-01T18:19:06.648701042Z              ^
> 
> 2024-02-01T18:19:06.648705242Z 
> 
> 2024-02-01T18:19:06.648709370Z TypeError: Cannot convert undefined or null to object
> 
> 2024-02-01T18:19:06.648722580Z     at Function.keys (<anonymous>)
> 
> 2024-02-01T18:19:06.648727140Z     at wrapper (/home/node/app/node_modules/wrappy/wrappy.js:27:14)
> 
> 2024-02-01T18:19:06.648730948Z     at Function.Client.scrape (/home/node/app/node_modules/bittorrent-tracker/client.js:120:8)
> 
> 2024-02-01T18:19:06.648735060Z     at /home/node/app/lib/torrent.js:47:16
> 
> 2024-02-01T18:19:06.648738844Z     at /home/node/app/node_modules/async/dist/async.js:2583:44
> 
> 2024-02-01T18:19:06.648742612Z     at eachOfArrayLike (/home/node/app/node_modules/async/dist/async.js:506:13)
> 
> 2024-02-01T18:19:06.648758836Z     at eachOf (/home/node/app/node_modules/async/dist/async.js:626:16)
> 
> 2024-02-01T18:19:06.648763153Z     at awaitable (/home/node/app/node_modules/async/dist/async.js:211:32)
> 
> 2024-02-01T18:19:06.648767133Z     at Object.eachLimit (/home/node/app/node_modules/async/dist/async.js:2686:16)
> 
> 2024-02-01T18:19:06.648771065Z     at Object.awaitable (/home/node/app/node_modules/async/dist/async.js:211:32)
> 
> 2024-02-01T18:19:06.648774908Z     at /home/node/app/lib/torrent.js:46:11
> ```

I've not long just set the var to TRUE to test this and got the same as you.
