### ISSUE TITLE
Parameters undefined

### ISSUE THREAD

**Issue by ash32152** [Gabisonfire/torrentio-scraper-sh#41]
**Describe the bug**
Pulled the latest commit over the top of the fork and get parameters undefined

**To Reproduce**
check logs of consumer after docker compose up -d 
**Expected behavior**
processing torrents
**Logs**
Provide logs for all containers when this issue occurs. 
If the logs are short, make sure to triple backtick them, or use https://pastebin.com/

2024-02-02T17:04:56.307005479Z     sql: "SELECT i.relname AS name, ix.indisprimary AS primary, ix.indisunique AS unique, ix.indkey AS indkey, array_agg(a.attnum) as column_indexes, array_agg(a.attname) AS column_names, pg_get_indexdef(ix.indexrelid) AS definition FROM pg_class t, pg_class i, pg_index ix, pg_attribute a WHERE t.oid = ix.indrelid AND i.oid = ix.indexrelid AND a.attrelid = t.oid AND t.relkind = 'r' and t.relname = 'files' GROUP BY i.relname, ix.indexrelid, ix.indisprimary, ix.indisunique, ix.indkey ORDER BY i.relname;",

2024-02-02T17:04:56.307009346Z     parameters: undefined

2024-02-02T17:04:56.307012292Z   },

2024-02-02T17:04:56.307015269Z   original: error: cache lookup failed for attribute 1 of relation 30294

2024-02-02T17:04:56.307019499Z       at Parser.parseErrorMessage (/app/node_modules/pg-protocol/dist/parser.js:287:98)

2024-02-02T17:04:56.307022693Z       at Parser.handlePacket (/app/node_modules/pg-protocol/dist/parser.js:126:29)

2024-02-02T17:04:56.307025727Z       at Parser.parse (/app/node_modules/pg-protocol/dist/parser.js:39:38)

2024-02-02T17:04:56.307029442Z       at Socket.<anonymous> (/app/node_modules/pg-protocol/dist/index.js:11:42)

2024-02-02T17:04:56.307032601Z       at Socket.emit (node:events:518:28)

2024-02-02T17:04:56.307035555Z       at addChunk (node:internal/streams/readable:559:12)

2024-02-02T17:04:56.307038513Z       at readableAddChunkPushByteMode (node:internal/streams/readable:510:3)

2024-02-02T17:04:56.307041551Z       at Readable.push (node:internal/streams/readable:390:5)

2024-02-02T17:04:56.307044518Z       at TCP.onStreamRead (node:internal/stream_base_commons:190:23) {

2024-02-02T17:04:56.307047525Z     length: 116,

2024-02-02T17:04:56.307050462Z     severity: 'ERROR',

2024-02-02T17:04:56.307053388Z     code: 'XX000',

2024-02-02T17:04:56.307056325Z     detail: undefined,

2024-02-02T17:04:56.307059256Z     hint: undefined,

2024-02-02T17:04:56.307062306Z     position: undefined,

2024-02-02T17:04:56.307068626Z     internalPosition: undefined,

2024-02-02T17:04:56.307071636Z     internalQuery: undefined,

2024-02-02T17:04:56.307074542Z     where: undefined,

2024-02-02T17:04:56.307077436Z     schema: undefined,

2024-02-02T17:04:56.307080355Z     table: undefined,

**Hardware:**
 - OS and distro: [e.g. Raspberry Pi OS, Ubuntu, Rocky]
 - Server: [e.g. VM, Baremetal, Pi]
docker
**Additional context**

dropped in new volumes in case schema wise had changed and does it on a complete new install

**Comment by purple-emily** [comment]
Can you confirm no changes after cloning the new repo?

**Comment by ash32152** [comment]
I hadn't although please ignore, local issue and have resolved, thanks for the reply! :)
